apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fileblock-localdir
provisioner: fileblock.csi
parameters:
  backingStore.type: local
  backingStore.local.path: /var/lib/fileblock-localdir
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
