apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fileblock-system

resources:
  - ../../base
  - storageclass.yaml

patches:
  - path: patch-controller.yaml
    target:
      kind: Deployment
      name: fileblock-controller
  - path: patch-node.yaml
    target:
      kind: DaemonSet
      name: fileblock-node
