apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileblock-controller
  namespace: fileblock-system
spec:
  template:
    spec:
      containers:
        - name: fileblock-controller
          imagePullPolicy: IfNotPresent
          args:
            - --endpoint=unix:///csi/csi.sock
            - --backing-store=/var/lib/fileblock
            - --topology-key=fileblock.csi/backing-store
            - --log-level=debug
