apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fileblock
provisioner: fileblock.csi
parameters:
  backingStore.type: local
  backingStore.local.path: /srv/fileblock-source
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
