apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fileblock-e2e
provisioner: fileblock.csi
parameters:
  backingStore.type: local
  backingStore.local.path: /tmp/fileblock-e2e
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
